Repository cse110-fa21-group4/cse110-fa21-group4, pull requests merged in 2021-11, with the labels that each got.

#66 UI
  src/home.css
  src/home.html
  src/recipe_expand/img/5-star.svg
  src/recipe_expand/img/bread.jpg
  src/recipe_expand/img/logo.jpg
  src/recipe_expand/recipe_expand.css
  src/recipe_expand/recipe_expand.html
  src/recipe_list/img/grain.jpeg
  src/recipe_list/recipe_list.css
  src/recipe_list/recipe_list.html
  src/recipe_list/scripts/Main.js
  src/recipe_list/scripts/RecipeCard.js
  src/scripts/RecipeCard.js
  src/scripts/main.js
  src/scripts/sideBar.js
Labels: enhancement, backend, frontend

#71 PR just so that everyone has the fixed structure + hyperlinks
  .github/workflows/linter.yml
  src/home/home.css
  src/home/home.html
  src/home/img/bread_logo.jpg
  src/home/img/favicon.ico
Labels: frontend

#75 Search Bar Done and Documentation Fixed in main.js
  src/home/home.html
  src/recipe_list/recipe_list.css
  src/recipe_list/recipe_list.html
  src/scripts/RecipeCard.js
  src/scripts/RecipeList.js
  src/scripts/Router.js
  src/scripts/addRecipe.js
  src/scripts/main.js
  src/scripts/searchKey.js
Labels: documentation, backend

#79 Connects recipe list to recipe expand + navbar
  src/home/home.css
  src/home/home.html
  src/recipe_expand/recipe_expand.css
  src/recipe_expand/recipe_expand.html
  src/recipe_list/img/fullStar.png
  src/recipe_list/img/hollowStar.png
  src/recipe_list/recipe_list.html
  src/scripts/RecipeCard.js
  src/scripts/RecipeCardExpand.js
  src/scripts/RecipeList.js
  src/scripts/main.js
  src/scripts/recipeExpand.js
  src/scripts/searchKey.js
Labels: frontend

#86 Cook view and update works now :)
  src/recipe_expand/recipe_expand.html
  src/scripts/RecipeCardExpand.js
  src/scripts/RecipeList.js
  src/scripts/deleteRecipe.js
  src/scripts/main.js
  src/scripts/recipeExpand.js
Labels: enhancement, backend, frontend
