Repository cse110-fa21-group4/cse110-fa21-group4, pull requests merged in 2021-12, with the labels that each got.

#89 implementing delete button onto recipe cards and taking delete out of…
  src/scripts/RecipeCard.js
  src/scripts/recipeExpand.js
Labels: backend, frontend

#96 Add recipe works now
  src/recipe_list/recipe_list.html
  src/scripts/FavoriteList.js
  src/scripts/RecipeList.js
  src/scripts/addRecipe.js
  src/scripts/main.js
Labels: backend, frontend

#98 All hashmaps work with added recipe now, alerts work for duplicated or deleted/hidden
  src/scripts/addRecipe.js
  src/scripts/main.js
Labels: bug, backend

#100 UI to main for new styling
  home.css
  src/home/home.css
  src/home/home.html
  src/home/img/bread-bg.jpg
  src/home/img/bread-bg2.jpg
  src/recipe_expand/recipe_expand.css
  src/recipe_expand/recipe_expand.html
  src/recipe_list/recipe_list.css
  src/recipe_list/recipe_list.html
  src/scripts/RecipeCard.js
  src/scripts/RecipeCardExpand.js
  src/scripts/recipeExpand.js
Labels: frontend

#103 Update insert position and add enter key for addRecipe
  package-lock.json
  src/scripts/CookView.js
  src/scripts/FavoriteList.js
  src/scripts/FavoriteRecipe.js
  src/scripts/RecipeCard.js
  src/scripts/RecipeCardExpand.js
  src/scripts/RecipeList.js
  src/scripts/addRecipe.js
  src/scripts/apiComplexSearch.js
  src/scripts/cookViewInit.js
  src/scripts/deleteRecipe.js
  src/scripts/genericFetch.js
  src/scripts/main.js
  src/scripts/popularRecipes.js
  src/scripts/recipeExpand.js
  src/scripts/searchKey.js
  src/scripts/sideBar.js
Labels: backend, frontend

#111 UI BUGFIX ELECTRIC BOOGALOO 2.0
  src/cook_view/cook_view.html
  src/favorites/favorites.html
  src/home/home.css
  src/scripts/RecipeList.js
  src/scripts/addRecipe.js
  testfile.txt
Labels: frontend

#121 Homepage Search Bar Delete/Delete button changed
  src/favorites/favorites.html
  src/home/home.css
  src/home/home.html
  src/recipe_expand/recipe_expand.css
  src/recipe_expand/recipe_expand.html
  src/recipe_list/img/delete.png
  src/recipe_list/recipe_list.css
  src/recipe_list/recipe_list.html
  src/scripts/RecipeCard.js
Labels: frontend

#125 fix form refreshing page when using enter
  src/scripts/RecipeCardExpand.js
Labels: bug, backend

#126 Manual Testing md
  specs/testing/manual-testing.md
Labels: documentation, ci/cd phase 2
